pipeline {
    agent any
    stages {
        stage ('Compile Stage') {
            steps {
                withMaven(maven : 'Maven3.6') {
                    bat 'C:\Program Files\Java\jdk-13.0.2\bin mvn -f JenkinsJ/pom.xml clean compile'
                    
                   }
            }
        }
        stage ('Testing Stage') {
            steps {
                withMaven(maven : 'Maven3.6') {
                    bat 'C:\Program Files\Java\jdk-13.0.2\bin mvn -f JenkinsJ/pom.xml test'
                }
            }
        }
        stage ('Deployment Stage') {
            steps {
                withMaven(maven : 'Maven3.6') {
                    bat 'C:\Program Files\Java\jdk-13.0.2\bin mvn -f JenkinsJ/pom.xml deploy'
                }
            }
        }
    }
}